### ISSUE TITLE
[Config] Push type

### ISSUE THREAD

**Issue by Strauman** [Strauman/travis-latexbuild#8] opened 2018-09-19 09:36 UTC
Relates to #3 ;
- [x] none
- [x] branch
- [ ] release

**Comment by PHPirates** [comment] 2018-11-15 16:35
Now it's a duplicate of #3, sort of

**Closed as completed by PHPirates** 2018-11-15 16:35 UTC
Labels: duplicate

**Comment by Strauman** [comment] 2018-11-18 15:02
Yes, but we could make it like a built-in feature at some point?
